name: get latest release of grafana and prometheus
on:
  schedule:
    - cron: "30 18 * * 4" 
jobs:
  build:
    name: Get latest release
    runs-on: ubuntu-latest
    steps:
      - id: prometheus
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: prometheus/https://github.com/prometheus/prometheus/releases
      - id: grafana
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: grafana/https://github.com/grafana/grafana/releases
      - uses: actions/checkout@v2
      - name: create a file
        run: |
          echo "Prometheus latest release is ${{ steps.prometheus.outputs.value }}"
          echo "Prometheus latest release is ${{ steps.grafana.outputs.value }}"
#       - uses: docker/build-push-action@v1
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           repository: pozetroninc/keydb-timeseries
#           dockerfile: timeseries.dockerfile
#           build_args: KEY_DB_VERSION=${{ steps.keydb.outputs.release }}, REDIS_TIME_SERIES_VERSION=${{ steps.timeseries.outputs.release }}
#           tags: latest, ${{ steps.keydb.outputs.release }}_${{ steps.timeseries.outputs.release }}
